version: "3.9"
services:
  auth_db:
    container_name: auth_db
    image: postgres:15.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "auth_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      start_period: 10s

networks:
  app-net: